export const UPDATE_ORDER_INFO = 'UPDATE_ORDER_INFO';
export const UPDATE_CART_LIST = 'UPDATE_CART_LIST';
export const UPDATE_STUDENT_INFO = 'UPDATE_STUDENT_INFO';
export const UPDATE_CARL_STATUS = 'UPDATE_CARL_STATUS';
export const UPDATE_TRANSFORM_CLASS = 'UPDATE_TRANSFORM_CLASS';