export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';
export const UPDATE_AUTHOR_INFO = 'UPDATE_AUTHOR_INFO';
export const UPDATE_CODE = 'UPDATE_CODE';
export const UPDATE_SYSTEMINFO = 'UPDATE_SYSTEMINFO';
export const UPDATE_LOGININFO = 'UPDATE_LOGININFO';
export const UPDATE_CARTLIST = 'UPDATE_CARTLIST';